ALTER TABLE "Offer" ADD COLUMN "soldQuantity" INTEGER;
ALTER TABLE "Offer" ADD COLUMN "sellerLevel" TEXT;
ALTER TABLE "Offer" ADD COLUMN "fullShipping" BOOLEAN NOT NULL DEFAULT 0;

INSERT OR IGNORE INTO "Niche" ("id", "name", "wantedKeywords", "enabledStores") VALUES
('catalog-technology', 'Tecnologia, Gamer & Eletrônicos', '["smartphone custo beneficio","fone bluetooth cancelamento ruido","teclado mecanico switch red","mouse gamer rgb leve","monitor ultrawide 144hz","headset gamer surround","ring light profissional","microfone condensador usb","lampada inteligente wifi","alexa echo dot","fire tv stick","smartwatch amoled","power bank 20000mah carregamento rapido","carregador inducao","ssd nvme 1tb","placa de video custo beneficio","roteador wi-fi 6 gigabit"]', '["mercado_livre"]'),
('catalog-home', 'Casa, Cozinha Moderna & Eletroportáteis', '["air fryer 12l forno","panela eletrica pressao digital","aspirador robo mapeamento","liquidificador alta potencia copo inox","cafeteira eletrica programavel","purificador de agua com compressor","kit panelas ceramica antiaderente","organizador modular geladeira","suporte articulado tv","ferro de passar a vapor vertical","ventilador coluna silencioso","umidificador de ar ultrassonico","torneira eletrica cozinha","fritadeira sem oleo 4l"]', '["mercado_livre"]'),
('catalog-beauty', 'Beleza, Cuidados Pessoais & Estética', '["secador cabelo profissional ionico","modelador de cachos automatico","prancha alisadora titanium","maquina cortar cabelo profissional cordless","epilador eletrico","escova rotativa secadora","kit skincare acido hialuronico","vitamina c rosto","perfume importado masculino mais vendido","perfume importado feminino lancamento","kit cronograma capilar profissional","massageador facial eletrico"]', '["mercado_livre"]'),
('catalog-sports', 'Esportes, Fitness & Ar Livre', '["kit halteres ajustaveis","barra fixa porta","colchonete yoga espesso","conjunto fitness feminino ginastica","tenis corrida amortecimento","mochila impermeavel camping","barraca camping 4 pessoas","colchao inflavel casal","bicicleta ergometrica magnetica","estacao de musculacao compacta","smartband esporte","garrafa termica aco inox 1l"]', '["mercado_livre"]'),
('catalog-fashion', 'Moda, Calçados & Acessórios', '["tenis casual masculino conforto","tenis feminino ortopedico","mochila executiva notebook usb","bolsa feminina couro sintetica","carteira masculina couro rfid","oculos sol polarizado","relogio masculino prova d agua","mala de viagem rodinhas 360"]', '["mercado_livre"]'),
('catalog-tools', 'Ferramentas, Construção & Utilidades', '["parafusadeira furadeira bateria litio","kit ferramentas completo maleta","esmerilhadeira angular","medidor laser distancia","camera seguranca wifi externa giratoria","fechadura digital biometrica","mangueira elastica retratil","aparador de grama eletrico"]', '["mercado_livre"]'),
('catalog-pets', 'Pets', '["bebedouro fonte gato inox","comedouro automatico racao","tapete higienico lavavel super absorvente","cama pet ortopedica grande","brinquedo interativo pet dispensador","caixa transporte pet aprovada"]', '["mercado_livre"]'),
('catalog-automotive', 'Automotivo & Motos', '["camera de re retrovisor","multimidia android auto carplay","aspirador automotivo potente 12v","carregador veicular saida usb c","suporte celular magnetico saida ar","capa automotiva impermeavel protecao uv","rastreador veicular gps discreto"]', '["mercado_livre"]');
