import { db } from '../src/server/db.js';
import { calculateDiscount, formatOfferMessage, scoreOffer, type OfferInput } from '../src/server/domain.js';

const products: Array<OfferInput & { previousPrice?: number }> = [
  { externalId:'affiliate-MLB2766771378',storeId:'mercado_livre',title:'Creatina 1kg Suplemento Monohidratada em pó 100% Pura - Soldiers Nutrition',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_894230-MLA111390627295_052026-AB.webp',originalUrl:'https://www.mercadolivre.com.br/creatina-1kg-suplemento-monohidratada-em-po-100-pura-soldiers-nutrition/p/MLB18725310?pdp_filters=item_id%3AMLB2766771378',affiliateUrl:'https://meli.la/2kdeeA4',currentPrice:59.90,previousPrice:239.90,rating:4.8,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB6824078526',storeId:'mercado_livre',title:'Tênis Asics Academia Corrida Treino Macio Garantia envio já',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_847985-MLB111070321434_052026-AB-tnis-asics-academia-corrida-treino-macio-garantiaenvioja.webp',originalUrl:'https://produto.mercadolivre.com.br/MLB-6824078526-tnis-asics-academia-corrida-treino-macio-garantiaenvioja-_JM',affiliateUrl:'https://meli.la/163Ymzc',currentPrice:99.90,previousPrice:333,rating:5,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB4103147311',storeId:'mercado_livre',title:'Máquina de Acabamento para Cabelo, Barba e Pelos Kemei 032',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_809090-MLB112050371271_052026-AB.webp',originalUrl:'https://www.mercadolivre.com.br/maquina-acabamento-cortar-cabelo-barba-e-pelos-kemei-032/up/MLBU3256334594?pdp_filters=item_id%3AMLB4103147311',affiliateUrl:'https://meli.la/2xChang',currentPrice:37.52,previousPrice:78.90,rating:4.7,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB3993443301',storeId:'mercado_livre',title:'Bicicleta Ergométrica Spinning Liftness X11 Brusfit',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_957793-MLA114373238664_082026-AB.webp',originalUrl:'https://www.mercadolivre.com.br/brus-fit-bicicleta-ergometrica-spinning-liftness-x11-cor-pretovermelho-brusfit/p/MLB28263665',affiliateUrl:'https://meli.la/33abbdU',currentPrice:435.94,previousPrice:839,rating:4.7,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB4345564271',storeId:'mercado_livre',title:'Parafusadeira Furadeira com 2 Baterias, Maleta e Kit Completo Simake',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_641541-MLA111608975062_062026-AB.webp',originalUrl:'https://www.mercadolivre.com.br/parafusadeira-furadeira-c-2-baterias-maleta-kit-completo-led-eixo-flexivel-varios-niveis-torque-simake/p/MLB50181290',affiliateUrl:'https://meli.la/2nky47S',currentPrice:124.71,previousPrice:299,rating:4.7,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB3621404839',storeId:'mercado_livre',title:'Lavadora Lava Jato Portátil de Pressão com 2 Baterias e Maleta',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_710675-MLB89102120983_082025-AB.webp',originalUrl:'https://www.mercadolivre.com.br/lavadora-lava-jato-portatil-pressao-2-baterias--maleta/up/MLBU605239077?pdp_filters=item_id%3AMLB3621404839',affiliateUrl:'https://meli.la/2qSJVcu',currentPrice:98,previousPrice:229.90,rating:4.5,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB4233789327',storeId:'mercado_livre',title:'Carregador Turbo 40W Compatível com iPhone, USB Tipo C Duplo',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_738459-MLA107707152120_032026-AB.webp',originalUrl:'https://www.mercadolivre.com.br/carregador-turbo-40w-compativel-com-iphone-8-x-xr-11-12-13-14-pro-max-usb-tipo-c-duplo/p/MLB56625214?pdp_filters=item_id%3AMLB4233789327',affiliateUrl:'https://meli.la/27bRjeH',currentPrice:33,previousPrice:79.11,rating:4.8,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB4598463015',storeId:'mercado_livre',title:'Perfume Nautica Voyage Eau de Toilette Masculino 100ml',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_856898-MLA87999531628_072025-AB.webp',originalUrl:'https://www.mercadolivre.com.br/perfume-nautica-voyage-eau-de-toilette-masculino-100ml/p/MLB8729164',affiliateUrl:'https://meli.la/2Y7rFPs',currentPrice:104,rating:4.8,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB3950877881',storeId:'mercado_livre',title:'Gel Creme Hidratante Facial Garnier Vitamina C 85g',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_828744-MLA81925003571_012025-AB.webp',originalUrl:'https://www.mercadolivre.com.br/gel-creme-hidratante-facial-antimanchas-toque-seco-com-vitamina-c-controla-a-oleosidade-e-uniformiza-a-pele-garnier-85g/p/MLB44895020',affiliateUrl:'https://meli.la/1e4uqmU',currentPrice:24.55,previousPrice:44.59,rating:4.9,shipping:'Consulte o frete no anúncio',stock:1 },
  { externalId:'affiliate-MLB4671001438',storeId:'mercado_livre',title:'Fritadeira sem Óleo Air Fryer Mondial 4L 1500W AFN-40-BFT',imageUrl:'https://http2.mlstatic.com/D_Q_NP_2X_775407-MLA99776749612_122025-AB.webp',originalUrl:'https://www.mercadolivre.com.br/fritadeira-sem-oleo-air-fryer-4l-mondial-1500w-afn-40-bft/p/MLB22530387',affiliateUrl:'https://meli.la/2WMPLsz',currentPrice:267.74,previousPrice:716.90,rating:4.9,shipping:'Consulte o frete no anúncio',stock:1 },
];

await db.store.upsert({ where:{id:'mercado_livre'}, update:{enabled:true,integrationStatus:'connected'}, create:{id:'mercado_livre',name:'Mercado Livre',enabled:true,integrationStatus:'connected'} });
const niche = await db.niche.upsert({ where:{name:'Produtos de afiliado'}, update:{active:true}, create:{name:'Produtos de afiliado',wantedKeywords:'[]',minDiscount:0,maxOffers:100,active:true} });

for (const product of products) {
  const score = scoreOffer(product);
  const offer = await db.offer.upsert({
    where:{storeId_externalId:{storeId:product.storeId,externalId:product.externalId}},
    update:{title:product.title,imageUrl:product.imageUrl,originalUrl:product.originalUrl,affiliateUrl:product.affiliateUrl,currentPrice:product.currentPrice,previousPrice:product.previousPrice,discountPercent:calculateDiscount(product.currentPrice,product.previousPrice),rating:product.rating,shipping:product.shipping,stock:product.stock,score,status:'approved',nicheId:niche.id,rawData:JSON.stringify({source:'mercado_livre_affiliate_hub',galleryImages:[product.imageUrl],collectedAt:new Date().toISOString()})},
    create:{...product,nicheId:niche.id,discountPercent:calculateDiscount(product.currentPrice,product.previousPrice),score,status:'approved',rawData:JSON.stringify({source:'mercado_livre_affiliate_hub',galleryImages:[product.imageUrl],collectedAt:new Date().toISOString()})},
  });
  await db.affiliateLink.upsert({where:{id:`affiliate-link-${offer.id}`},update:{url:product.affiliateUrl!,source:'mercado_livre_affiliate_hub'},create:{id:`affiliate-link-${offer.id}`,offerId:offer.id,url:product.affiliateUrl!,source:'mercado_livre_affiliate_hub'}});
  await db.publication.upsert({where:{id:`queue-${offer.id}`},update:{message:formatOfferMessage(product)},create:{id:`queue-${offer.id}`,offerId:offer.id,message:formatOfferMessage(product)}});
}

console.log(`${products.length} produtos afiliados importados.`);
await db.$disconnect();
